CREATE TABLE icd10
(
  "ID" INT PRIMARY KEY,
  "REC_CODE" VARCHAR(50),
  "MKB_CODE" VARCHAR(50),
  "MKB_NAME" VARCHAR(1000),
  "ID_PARENT" INT,
  "ADDL_CODE" VARCHAR(50),
  "ACTUAL" INT,
  "DATE" DATE
)